[package]
name = "umidedup"
version = "0.1.0"
authors = ["Arno Velds <a.velds@nki.nl>", "Roel Kluin <r.kluin@nki.nl>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.43"
atoi = "1.0.0"
umibk = { path = "../../umibk/" }
tokio = { version = "1.11", features = ["fs", "io-std", "macros", "rt"] }
noodles-bam = { version = "0.15.0", features = ["async"] }
noodles-sam = "0.12.0"
noodles-bgzf = { version = "0.9.0", features = ["async"] }
#noodles-bam = {path = "../crates/noodles/noodles-bam", features = ["async"]}
#noodles-sam = {path = "../crates/noodles/noodles-sam"}
clap = "3.1.0"
thiserror = "1.0.28"
regex = "1.5.4"
itertools = "0.10.1"
ahash = "0.7.6"
smallvec = "1.7.0"

[profile.release]
debug = 1
